### DISCUSSION TITLE
global.less 覆盖 css module

### DISCUSSION THREAD

**Discussion by jintangWang** [umijs/umi#10255] [Q&A]
`umi` 版本：3.5.0
`global.less` 定义的样式:
``` less
.mobile-drawer {
  .ant-drawer-body {
    background-color: #181A27;
    padding: 20px 20px 35px 20px;
  }
}
```
`module` 中定义样式：
``` less
.buyModal {
  :global {
    .ant-drawer-body {
      background: #181A27;
      padding: 12px 20px 0;
    }
  }
}
```
生成的样式权重一样，但是`global.less` 会在后面，覆盖 `module` 的样式。请问怎么调整，请不要说加 `!important` 这种的答案。
![image](https://user-images.githubusercontent.com/12557847/211446969-19fc11ae-95b1-45db-ba62-f161680a0706.png)
