### DISCUSSION TITLE
为何在Docker环境中会卡死且无法热更新？

### DISCUSSION THREAD

**Discussion by Mr-HuanZi** [umijs/umi#10781] [Q&A]
我尝试在Docker中部署Ant Design Pro本地开发环境，但每次构建MFSU时都会导致容器卡死且整个Docker服务无响应，CPU和磁盘占用均为100%。

如果已经在src目录生成了.umi目录，容器可以正常运行，但是无法热更新了。

下面是我的构建代码
## Dockerfile
```
FROM node:18.15.0-alpine3.17

WORKDIR /app

COPY package.json package-lock.json .

# 设置环境变量
ENV NODE_OPTIONS=--openssl-legacy-provider

# 安装依赖
RUN npm config set registry http://registry.npmmirror.com -g && npm install --no-cache

# 拷贝项目目录进来
COPY . .

EXPOSE 8000

CMD ["npm", "run", "start"]
```

## docker-compose
```yml
version: '3.9'
services:
  node:
    container_name: node
    hostname: node
    build:
      context: E:\Develop\Project\antdpro
      dockerfile: Dockerfile
    volumes:
        - E:\Develop\Project\antdpro\src:/app/src
        - E:\Develop\Project\antdpro\config:/app/config
    restart: unless-stopped
```

## 我的本地环境
- Windows 10 + WSL2
