### ISSUE TITLE
css module嵌套写法不生效

### ISSUE THREAD

**Issue by CX330-jiuxi** [umijs/umi#11111]
## What happens?

使用cssModule写法，在部分电脑上，样式不生效

## Mini Showcase Repository(REQUIRED)
`.layout`下有个`.content`，
```css
.layout {
  width: 100%;
  height: 100%;
  display: flex;
  flex-direction: column;

  .content {
    margin-top: 3px;
    flex: 1 1 auto;
    overflow: hidden;
  }
}
```
css文件已经加载
![WechatIMG12](https://user-images.githubusercontent.com/51979013/236769786-23be7d21-92ce-45ba-81ae-92405e636f85.png)

![WechatIMG13](https://user-images.githubusercontent.com/51979013/236769805-dee53715-1663-49d1-8949-6ae5871c8305.png)

但是如图，样式并未生效
![WechatIMG11](https://user-images.githubusercontent.com/51979013/236769358-53962276-2ef2-4c78-ae03-cd6cbfa1984e.png)

改成`less`后生效

<img width="1044" alt="image" src="https://user-images.githubusercontent.com/51979013/236770948-e9c821b0-475e-41d2-9cf7-d2d9246f98e9.png">

![WechatIMG14](https://user-images.githubusercontent.com/51979013/236770560-83855c29-cc19-49f5-ac4c-57857820642d.png)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Umi Version**:^4.0.65
- **Node Version**:v16.17.0
- **Platform**:windows
