### ISSUE TITLE
[Bug] legacy mode模式下，css没有添加webkit前缀

### ISSUE THREAD

**Issue by Pulset** [umijs/umi#11907]
## What happens?

<img width="1838" alt="image" src="https://github.com/umijs/umi/assets/21022593/429a905a-cb4c-4c0a-829f-2d746835380a">

picker-view.css中是有样式的，但是浏览器没有生效
``` css
.adm-picker-view-mask-top {
background: var(--adm-color-background);
-webkit-mask: linear-gradient(0deg, rgba(0, 0, 0, 0.6) 0%, rgba(0, 0, 0, 0.8) 50%, #000000 100%);
mask: linear-gradient(0deg, rgba(0, 0, 0, 0.6) 0%, rgba(0, 0, 0, 0.8) 50%, #000000 100%);
}
```
当umi legacy mode开启的时候会出现问题，关闭的时候正常。
## Mini Showcase Repository(REQUIRED)

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

https://codesandbox.io/p/sandbox/brave-neco-q6q4mj?file=%2Fsrc%2Findex.tsx
## How To Reproduce

**Steps to reproduce the behavior:** 1. 开启legacy mode

**Expected behavior** 1. css正常

## Context

- **Umi Version**: 4.0.81
- **Node Version**: 16.20.2
- **Platform**: mac
