### ISSUE TITLE
[Bug] github action workflow安装失败

### ISSUE THREAD

**Issue by mdddj** [umijs/umi#12310]
## What happens?

github action workflow运行安装失败

## Mini Showcase Repository(REQUIRED)

https://github.com/mdddj/blog

可以看到这里失败了: https://github.com/mdddj/blog/actions/runs/8756041711/job/24031561538

## How To Reproduce

提交代码到仓库后执行workflow

## Context

- **Umi Version**: 4.1.10
- **Node Version**: 20.3.1
- **Platform**: macos

**Comment by fz6m** [comment]
你贴的这一次构建目测是 github action 不稳定下载依赖挂了导致的，因为你指定的 npmrc 是从 cnpm 下，没官方源快，重试一次应该就好了。

试一下这个吧：

```yaml
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 如果用的不是 pnpm ，就不需要这一步
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          run_install: false
          version: 9 # 这一行可以不指定，但是需要在 `package.json#packageManager` 指定版本
      
      - name: Use Node.js v20
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: 'pnpm' # 如果是其他的包管理器，就填成对应的名字
      
      - name: Install dependencies
        run: pnpm i

      - name: Build
        run: |
          pnpm build
```
