### ISSUE TITLE
非根目录部署静态资源引用的问题

### ISSUE THREAD

**Issue by qianduanMortal** [umijs/umi#1697]
场景描述：
1，项目部署在nginx非根目录下。
2，public文件夹下，有静态资源若干（js,css,image）。
3，配置项中：publicPath:'/path/'
4，在document.ejs中引用资源方式如下：
`<link rel="icon" href="<%= context.publicPath %>favicon.png" type="image/x-icon">`
(正常访问到)
5，在普通组件中：
`<image src=`${publicPath}image/a.png`>`
(正常访问到)

问题描述：
在css或者less中背景图片怎么写才能正常访问到？

**Comment by qianduanMortal** [comment]
> 有一个 cssPublicPath 的配置，是不是你需要的？

umi已经升级到最高版本，请问配置完cssPublicPath以后，css里面的图片路径需要怎么写？

**Comment by imhele** [comment]
如果图片在本地的话，直接用相对路径就行，umi 打包时会把路径替换到 cssPublicPath 下。
比如：
`cssPublicPath: https://cdn.domain.com/css/`
```less
/* src/pages/Login/styles.less */
.avatar:empty {
  background-repeat: no-repeat;
  background-image: url('../assets/avatar/cb032b06ddc63a4dd4993e280e94be72.svg');
  /* file: src/assets/avatar/cb032b06ddc63a4dd4993e280e94be72.svg */
}
```
`build` 后 `https://cdn.domain.com/css/static/b14c50521e096a290af606ce3227327e.f3394d69.svg` (开启了hash)
