### ISSUE TITLE
不在项目中安装umi找不到sass的插件

### ISSUE THREAD

**Issue by Spaceman007** [umijs/umi#443]
已安装 sass-loader 和 node-sass，.webpackrc.js 添加了 sass 选项：
```js
export default {
    sass: {}
}
```
官网上没有 sass 的示例，不知道该怎么配置...

像下面这样的 scss，内部的 a 没有输出
```css
.container {
    a {
        color: #000000;
    }
}
```
