### ISSUE TITLE
useLocation 返回 location 的 TypeScript 类型声明有误

### ISSUE THREAD

**Issue by onlyling** [umijs/umi#4777]
## What happens?

useLocation 返回 location 的 TypeScript 类似声明有误，缺少 query 的声明。

## Context

```
## console.log

hash: ""
pathname: "/news-manage"
query:
  size: "10"
  title: "323"
search: "?title=323&size=10"
```

```typescript
export function useLocation<S = H.LocationState>(): H.Location<S>;

export interface IRouteComponentProps<Params extends {
    [K in keyof Params]?: string;
} = {}, Query extends {
    [K in keyof Query]?: string;
} = {}> {
    children: JSX.Element;
    location: Location & {
        query: Query;
    };
    route: IRoute;
    history: History;
    match: match<Params>;
}
```

- **Umi Version**: 3.2.2
- **Node Version**: v12.14.1
- **Platform**: macOS 10.15.5
