### ISSUE TITLE
不使用CSS Modules模式，引入css文件失效

### ISSUE THREAD

**Issue by zhenwoo** [umijs/umi#4861]
## 不使用CSS Modules模式，引入css文件失效
最近使用umi构建一个项目，但是非常不喜欢CSS Modules的模式，但是引入css后样式完全失效，请问如何解决这个问题？
## 相关环境信息

- **Umi 版本**：umi 3X

**Comment by leftstick** [comment]
请提供可复现repo。

**Comment by zhenwoo** [comment]
> 请提供可复现repo。
### 使用umi脚手架创建的项目，什么都没有动，就改了className为css里面的class名
```css
.normal {
  font-family: Georgia, sans-serif;
  text-align: center;
}

.title {
  font-size: 2.5rem;
  font-weight: normal;
  letter-spacing: -1px;
  background: darkslateblue;
  padding: .6em 0;
  color: white;
  margin: 0;
}
```
```javascript
import React from 'react';
import './index.less';

const BasicLayout: React.FC = props => {
  return (
    <div className="normal">
      <h1 className="title">Yay! Welcome to umi!</h1>
      {props.children}
    </div>
  );
};

export default BasicLayout;`
