### ISSUE TITLE
命令行工具 help 信息补充完整

### ISSUE THREAD

**Issue by lleohao** [umijs/umi#5314]
## What happens?

```
❯ umi help generate

  Usage: umi generate [options]

  Options:

  Details:
```

## 相关环境信息

- **Umi 版本**：umi@3.2.18
- **Node 版本**：v14.4.0
- **操作系统**：macos
