### ISSUE TITLE
antd-mobile List的flex布局hacker属性umi在打包被滤掉

### ISSUE THREAD

**Issue by letcheng** [umijs/umi#723]
* 相关依赖
   *  antd-mobile 2.2.2
   *  umi  1.3.16

* antd-mobile的原文件

```css
.am-list-item .am-list-line {
  position: relative;
  display: -webkit-box;
  display: -webkit-flex;
  display: -ms-flexbox;
  display: flex;
  -webkit-box-flex: 1;
  -webkit-flex: 1;
  -ms-flex: 1;
  flex: 1;
  -webkit-align-self: stretch;
  -ms-flex-item-align: stretch;
  align-self: stretch;
  padding-right: 15px;
  overflow: hidden;
  /* list左侧主内容*/
  /* list右补充内容*/
  /* 辅助性文字*/
  /* list右侧箭头*/
}
```

* umi打包输出的文件

```css
  .am-list-item .am-list-line {
	position:relative;
	display:-ms-flexbox;
	display:flex;
	-ms-flex:1 1;
	flex:1 1;
	-ms-flex-item - align:stretch;
	align-self:stretch;
	padding-right:.3rem;
	overflow:hidden
}
```

> 最后只保留-ms相关的hacker，由于丢失 ·display: -webkit-flex·; 导致在iOS 8.x系统下，显示有兼容性问题。
