### ISSUE TITLE
[Bug]build后可能导致CSS样式失效（start时是正常的）

### ISSUE THREAD

**Issue by laeni** [umijs/umi#7944]
## What happens?

假设有如下CSS代码:
```css
.grayscale-1 {
  --tw-grayscale: grayscale(100%);
  filter: var(--tw-grayscale)
}

.grayscale-2 {
  --tw-xxx:  ;
  --tw-grayscale: grayscale(100%);
  filter: var(--tw-xxx) var(--tw-grayscale)
}
```
开发（npm run start）时，以上两个class`grayscale-1`和`grayscale-2`均生效，但是构建部署后只有`grayscale-1`会生效，`grayscale-2`中由于变量`--tw-xxx`是空值导致整个`filter`样式不生效。
如图所示: ![示例](https://github.com/laeni/issues-umi-build-css/blob/master/doc/Snipaste.png?raw=true)

## Mini Showcase Repository(REQUIRED)

<https://github.com/laeni/issues-umi-build-css>

## How To Reproduce

直接`npm run start`和`npm run build`即可，预期显示效果相同，但实际上不同。

## Context

- **Umi Version**: 3.5.21
- **Node Version**: 16.14.0
- **Platform**: Linux and Windows
